name: "🚩 Experimental Node"
on: 
  workflow_dispatch:   

permissions:
  contents: write
  pull-requests: none 
  issues: write
  packages: none

jobs:
  security-scoring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: OpenSSF Scorecard Monitor
        uses: ossf/scorecard-monitor@fix/last-relese
        with:
          scope: experimental_node/scope.json
          database: experimental_node/database.json
          report: experimental_node/report.md
          auto-commit: true
          auto-push: true
          generate-issue: true
          report-tags-enabled: true
          issue-title: "OpenSSF Scorecard Report Updated!"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-request-in-parallel: 10
          discovery-enabled: true
          discovery-orgs: 'nodejs'
      - name: Print the scores
        run: |
          echo '${{ steps.openssf-scorecard-monitor.outputs.scores }}'  
